# docker-compose version
version: "2.2"

# MAD services
services:
  mad_app:
    build: .
    container_name: mad_app
    cpu_count: 2
    cpu_percent: 50
    cpus: 0.5
    cpu_shares: 73
    cpu_quota: 50000
    cpu_period: 20ms
    cpuset: 0,1
    depends_on:
      - mad_db
      - mad_gen
      - mad_www
    entrypoint: ["wait-for-it", "--timeout=0", "mad_www:80", "--", "bash", "/app/init.sh"]
    image: mad
    links:
      - mad_db
    mem_limit: 2G
    memswap_limit: 4G
    restart: always
    volumes:
      - /home/traffic/pcapfile:/mad/pcap
      - /home/traffic/db/mad:/mad/dataset
  mad_gen:
    build: .
    container_name: mad_gen
    depends_on:
      - mad_db
      - mad_www
    entrypoint: ["wait-for-it", "--timeout=0", "mad_db:3306", "--", "bash", "/gen/init.sh"]
    image: mad
    links:
      - mad_db
    restart: always
    volumes:
      - /home/traffic/log/mad:/mad/report
      - /home/traffic/db/mad:/mad/dataset
  mad_www:
    build: .
    container_name: mad_www
    depends_on:
      - mad_db
    entrypoint: ["wait-for-it", "--timeout=0", "mad_db:3306", "--", "bash", "/www/init.sh"]
    image: mad
    links:
      - mad_db
    ports:
      - 8888:80
    restart: always
    volumes:
      - /home/traffic/log/mad:/mad/report
  mad_db:
    container_name: mad_db
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=deepocean
    expose:
      - 3306
    image: mysql:5.7
    networks:
      - default
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /home/traffic/log/mysql:/var/lib/mysql

# network settings
networks:
  default:
    driver: bridge
