version: '3'

services:
  mad:
    build: .
    network_mode: host
    links:
      - db
    volumes:
      - /home/traffic/pcapfile:/mad/pcap
    command: python3 /app/run_mad.py
    restart: "always"
  db:
    image: 'mysql:5.7'
    expose:
      - "3306"
    container_name: deepocean
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=mad
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - default
