# docker-compose version
version: "3"

# MAD sercives
services:
  mad_base:
    build: .
    container_name: mad_base
    image: mad
  mad_app:
    command: ["--path", "/mad/pcap"]
    depends_on:
      - mad_www
    links:
      - mad_db
    restart: on-failure
    volumes:
      - /data/httpdump:/mad/pcap
  mad_www:
    container_name: mad_www
    depends_on:
      - mad_base
      - mad_db
    entrypoint: bash /www/init.sh
    image: mad
    links:
      - mad_db
    ports:
      - 8888:80
    restart: on-failure
  mad_db:
    container_name: mad_db
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=deepocean
    expose:
      - 3306
    image: mysql:5.7
    networks:
      - default

# network settings
networks:
  default:
    driver: bridge
