# docker-compose version
version: "2.2"

# MAD services
services:
  mad_app:
    build: .
    container_name: mad_app
    cpus: 0.5
    cpu_shares: 75
    depends_on:
      - mad_db
      - mad_gen
      - mad_www
    entrypoint: ["wait-for-it", "--timeout=0", "mad_www:80", "--", "bash", "/app/init.sh"]
    image: mad
    links:
      - mad_db
    mem_limit: 96G
    memswap_limit: 192G
    restart: always
    volumes:
      - ./log/dataset:/mad/dataset
      - /root/traffic/pcapfile/tmp:/mad/pcap
#      - /home/traffic/pcapfile:/mad/pcap
      - /home/traffic/db/apt_model:/mad/model
      - /home/traffic/db/apt_retrain:/mad/retrain
  mad_gen:
    build: .
    container_name: mad_gen
    depends_on:
      - mad_db
      - mad_www
    entrypoint: ["wait-for-it", "--timeout=0", "mad_db:3306", "--", "bash", "/gen/init.sh"]
    image: mad
    links:
      - mad_db
    restart: always
    volumes:
      - ./log/dataset:/mad/dataset
      - /home/traffic/db/apt_report:/mad/report
  mad_www:
    build: .
    container_name: mad_www
    depends_on:
      - mad_db
    entrypoint: ["wait-for-it", "--timeout=0", "mad_db:3306", "--", "bash", "/www/init.sh"]
    image: mad
    links:
      - mad_db
    ports:
      - 8888:80
    restart: always
    volumes:
      - /home/traffic/db/apt_report:/mad/report
  mad_db:
    container_name: mad_db
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=deepocean
    expose:
      - 3306
    image: mysql:5.7
    networks:
      - default
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /home/traffic/db/apt_db:/var/lib/mysql

# network settings
networks:
  default:
    driver: bridge
