version: "3"

services:
  mad_app:
    build: .
    command: ["--path", "/mad/pcap"]
    image: mad
    links:
      - mad_db
    restart: on-failure
    volumes:
      - /data/httpdump:/mad/pcap
  mad_www:
    depends_on:
      - mad_db
    entrypoint: /www/init.sh
    image: mad
    links:
      - mad_db
    ports:
      - 8080:80
    restart: on-failure
  mad_db:
    container_name: mad_db
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=deepocean
    expose:
      - 3306
    image: mysql:5.7
    networks:
      - default

networks:
  default:
    driver: bridge
