# docker-compose version
version: "3"

# MAD sercives
services:
  mad_app:
    build: .
    container_name: mad_app
    depends_on:
      - mad_www
    entrypoint: ["wait-for-it", "mad_www:8888", "--", "python3", "/app/run_mad.py"]
    image: mad
    links:
      - mad_db
    restart: on-failure
    volumes:
      - /data/httpdump:/mad/pcap
  mad_www:
    build: .
    container_name: mad_www
    depends_on:
      - mad_db
    entrypoint: ["wait-for-it", "mad_db:3306", "--", "bash", "/www/init.sh"]
    image: mad
    links:
      - mad_db
    ports:
      - 8888:80
    restart: on-failure
  mad_db:
    container_name: mad_db
    environment:
      - MYSQL_ROOT_PASSWORD=zft13917331612
      - MYSQL_DATABASE=deepocean
    expose:
      - 3306
    image: mysql:5.7
    networks:
      - default

# network settings
networks:
  default:
    driver: bridge
